import type { Metadata } from 'next';

interface AppConfig {
  wssPort: number;
  metadata: Metadata;
  systemInfo: {
    cpuName: string;
    gpuName: string;
    motherBoardName: string;
  };
  pollingInterval: number;
}

const config: AppConfig = {
  wssPort: 6060,
  // 轮询间隔，建议不要低于1000
  pollingInterval: 2000,
  metadata: {
    title: 'ROG STRIX Monitor',
    description: 'Generated by create next app',
    manifest: '/manifest.json',
    themeColor: '#000000',
  },
  systemInfo: {
    cpuName: '13th Gen Intel(R) Core(TM) i9-13900K',
    gpuName: 'ROG Strix RTX4090 24G Gaming',
    motherBoardName: 'ROG Strix Z790-A Gaming WiFi',
  },
};

export default config;
